### ISSUE TITLE
Fix outcome.scala filename

### ISSUE THREAD

**Issue by amuttsch** [JanKoelzer/reactive-async#11]
The name of the file should be in uppercase `Outcome.scala`

**Comment by JanKoelzer** [comment]
According to the scala convention for multi unit file names http://docs.scala-lang.org/style/files.html#multi-unit-files the name should be lower case.
Anyway, I'd like the upstream to be refactored and names to be changed but don't feel qualified to do this.

**Comment by amuttsch** [comment]
Interesting, I just saw upper-case letters so it looked strange. Thanks for the link, learned sth. new.
